import { createContext, useState } from "react";

export const studentsContext = createContext()

export default function StudentsContext({ children }) {
    const [keys] = useState(["rollNo", "name", "education", "mobile", "email", "admissionDate"])
    const [data, setData] = useState([
        {
            id: 1,
            img: require("../assists/avatar/1.jpg"),
            rollNo: "01",
            name: "Tiger Nixon",
            education: "M.COM., P.H.D.",
            mobile: "123 456 7890",
            email: "info@example.com",
            admissionDate: "2011/04/25",
        },
        {
            id: 2,
            img: require("../assists/avatar/2.jpg"),
            rollNo: "02",
            name: "Garrett Winters",
            education: "M.COM., P.H.D.",
            mobile: "987 654 3210",
            email: "info@example.com",
            admissionDate: "2011/07/25",
        },
        {
            id: 3,
            img: require("../assists/avatar/3.jpg"),
            rollNo: "03",
            name: "Ashton Cox",
            education: "B.COM., M.COM.",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2009/01/12",
        },
        {
            id: 4,
            img: require("../assists/avatar/4.jpg"),
            rollNo: "04",
            name: "Cedric Kelly",
            education: "B.COM., M.COM.",
            mobile: "123 456 7890",
            email: "info@example.com",
            admissionDate: "2012/03/29",
        },
        {
            id: 5,
            img: require("../assists/avatar/5.jpg"),
            rollNo: "05",
            name: "Airi Satou",
            education: "B.A, B.C.A",
            mobile: "987 654 3210",
            email: "info@example.com",
            admissionDate: "2008/11/28",
        },
        {
            id: 6,
            img: require("../assists/avatar/6.jpg"),
            rollNo: "06",
            name: "Brielle Williamson",
            education: "B.COM., M.COM.",
            mobile: "123 456 7890",
            email: "info@example.com",
            admissionDate: "2012/12/02",
        },
        {
            id: 7,
            img: require("../assists/avatar/7.jpg"),
            rollNo: "07",
            name: "Herrod Chandler",
            education: "B.A, B.C.A",
            mobile: "987 654 3210",
            email: "info@example.com",
            admissionDate: "2012/08/06",
        },
        {
            id: 8,
            img: require("../assists/avatar/8.jpg"),
            rollNo: "08",
            name: "Rhona Davidson",
            education: "B.TACH, M.TACH",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2010/10/14",
        },
        {
            id: 9,
            img: require("../assists/avatar/9.jpg"),
            rollNo: "09",
            name: "Colleen Hurst",
            education: "B.A, B.C.A",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2009/09/15",
        },
        {
            id: 10,
            img: require("../assists/avatar/10.jpg"),
            rollNo: "10",
            name: "Sonya Frost",
            education: "B.COM., M.COM.",
            mobile: "123 456 7890",
            email: "info@example.com",
            admissionDate: "2008/12/13",
        },
        {
            id: 11,
            img: require("../assists/avatar/1.jpg"),
            rollNo: "11",
            name: "Jena Gaines",
            education: "B.TACH, M.TACH",
            mobile: "987 654 3210",
            email: "info@example.com",
            admissionDate: "2008/12/19",
        },
        {
            id: 12,
            img: require("../assists/avatar/2.jpg"),
            rollNo: "12",
            name: "Quinn Flynn",
            education: "B.TACH, M.TACH",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2013/03/03",
        },
        {
            id: 13,
            img: require("../assists/avatar/3.jpg"),
            rollNo: "13",
            name: "Charde Marshall",
            education: "B.A, B.C.A",
            mobile: "123 456 7890",
            email: "info@example.com",
            admissionDate: "2008/10/16",
        }, {
            id: 14,
            rollNo: "14",
            img: require("../assists/avatar/4.jpg"),
            name: "Haley Kennedy",
            education: "B.COM., M.COM.",
            mobile: "987 654 3210",
            email: "info@example.com",
            admissionDate: "2012/12/18",
        },
        {
            id: 15,
            rollNo: "15",
            img: require("../assists/avatar/5.jpg"),
            name: "Tatyana Fitzpatrick",
            education: "B.TACH, M.TACH",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2010/03/17",
        },
        {
            id: 16,
            rollNo: "16",
            img: require("../assists/avatar/6.jpg"),
            name: "Michael Silva",
            education: "B.A, B.C.A",
            mobile: "123 456 7890",
            email: "info@example.com",
            admissionDate: "2012/11/27",
        },
        {
            id: 17,
            rollNo: "17",
            img: require("../assists/avatar/7.jpg"),
            name: "Paul Byrd",
            education: "B.TACH, M.TACH",
            mobile: "987 654 3210",
            email: "info@example.com",
            admissionDate: "2010/06/09",
        },
        {
            id: 18,
            rollNo: "18",
            img: require("../assists/avatar/8.jpg"),
            name: "Gloria Little",
            education: "B.A, B.C.A",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2009/04/10",
        },
        {
            id: 19,
            rollNo: "19",
            img: require("../assists/avatar/9.jpg"),
            name: "Bradley Greer",
            education: "B.COM., M.COM.",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2012/10/13",
        },
        {
            id: 20,
            rollNo: "20",
            img: require("../assists/avatar/10.jpg"),
            name: "Dai Rios",
            education: "B.TACH, M.TACH",
            mobile: "123 456 7890",
            email: "info@example.com",
            admissionDate: "2012/09/26",
        },
        {
            id: 21,
            rollNo: "21",
            img: require("../assists/avatar/1.jpg"),
            name: "Jenette Caldwell",
            education: "B.A, B.C.A",
            mobile: "987 654 3210",
            email: "info@example.com",
            admissionDate: "2011/09/03",
        },
        {
            id: 22,
            rollNo: "22",
            img: require("../assists/avatar/2.jpg"),
            name: "Yuri Berry",
            education: "B.TACH, M.TACH",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2009/06/25",
        },
        {
            id: 23,
            rollNo: "23",
            img: require("../assists/avatar/3.jpg"),
            name: "Caesar Vance",
            education: "B.TACH, M.TACH",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2011/12/12",
        },
        {
            id: 24,
            rollNo: "24",
            img: require("../assists/avatar/4.jpg"),
            name: "Doris Wilder",
            education: "B.A, B.C.A",
            mobile: "123 456 7890",
            email: "info@example.com",
            admissionDate: "2010/09/20",
        },
        {
            id: 25,
            rollNo: "25",
            img: require("../assists/avatar/5.jpg"),
            name: "Angelica Ramos",
            education: "B.COM., M.COM.",
            mobile: "987 654 3210",
            email: "info@example.com",
            admissionDate: "2009/10/09",
        },
        {
            id: 26,
            rollNo: "26",
            img: require("../assists/avatar/6.jpg"),
            name: "Gavin Joyce",
            education: "B.TACH, M.TACH",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2010/12/22",
        },
        {
            id: 27,
            rollNo: "27",
            img: require("../assists/avatar/7.jpg"),
            name: "Jennifer Chang",
            education: "B.A, B.C.A",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2010/11/14",
        },
        {
            id: 28,
            rollNo: "28",
            img: require("../assists/avatar/8.jpg"),
            name: "Brenden Wagner",
            education: "B.TACH, M.TACH",
            mobile: "123 456 7890",
            email: "info@example.com",
            admissionDate: "2011/06/07",
        },
        {
            id: 29,
            rollNo: "29",
            img: require("../assists/avatar/9.jpg"),
            name: "Fiona Green",
            education: "B.A, B.C.A",
            mobile: "987 654 3210",
            email: "info@example.com",
            admissionDate: "2010/03/11",
        },
        {
            id: 30,
            rollNo: "30",
            img: require("../assists/avatar/10.jpg"),
            name: "Shou Itou",
            education: "B.COM., M.COM.",
            mobile: "(123) 4567 890",
            email: "info@example.com",
            admissionDate: "2011/08/14",
        }
    ])

    const removeItem = ({ id }) => {
        setData(prev => prev.filter(item => item.id !== id))
    }

    const addItem = (item) => {
        setData(prev => [...prev, { ...item, id: Math.max(...prev.map(({ id }) => id)) + 1 }])
    }

    return (
        <studentsContext.Provider value={{ data, removeItem, keys }}>
            {children}
        </studentsContext.Provider>
    )
}